### ISSUE TITLE
veritysetup fails with hash offsets bigger than 2gb

### ISSUE THREAD

**Issue by eviche** [nelenkov/cryptsetup#1]
/lib/utils.c#L74 --> r should be a 64 bit variable or it will overflow in line 108 with offsets bigger than 2gb, getting a negative number and failing line 109 check.

**Comment by nelenkov** [comment]
Thanks for your report. 

util.c is part of the cryptsetup code, so there's probably more than one place that needs to be fixed. If you have it working, please submit a pull request, and I will merge.

**Comment by eviche** [comment]
I think that the real problem is at lseek. Just fixing that veritysetup works fine.
Read and write operations could have the same problem if blocks bigger than 2gb were read or write but I don't think that is going to happen.
The other lseek calls in utils.c are ok.
I'm creating a pull request.

**Comment by nelenkov** [comment]
Thanks. I haven't tested this, but looks good and since it works for you, I've merged it.
